wandb_version: 1

exp_name:
  desc: null
  value: geoldm_qm9
train_diffusion:
  desc: null
  value: true
ae_path:
  desc: null
  value: null
trainable_ae:
  desc: null
  value: true
latent_nf:
  desc: null
  value: 1
kl_weight:
  desc: null
  value: 0.01
model:
  desc: null
  value: egnn_dynamics
probabilistic_model:
  desc: null
  value: diffusion
diffusion_steps:
  desc: null
  value: 1000
diffusion_noise_schedule:
  desc: null
  value: polynomial_2
diffusion_noise_precision:
  desc: null
  value: 1.0e-05
diffusion_loss_type:
  desc: null
  value: l2
n_epochs:
  desc: null
  value: 3000
batch_size:
  desc: null
  value: 64
lr:
  desc: null
  value: 0.0001
brute_force:
  desc: null
  value: false
actnorm:
  desc: null
  value: true
break_train_epoch:
  desc: null
  value: false
dp:
  desc: null
  value: true
condition_time:
  desc: null
  value: true
clip_grad:
  desc: null
  value: true
trace:
  desc: null
  value: hutch
n_layers:
  desc: null
  value: 9
inv_sublayers:
  desc: null
  value: 1
nf:
  desc: null
  value: 256
tanh:
  desc: null
  value: true
attention:
  desc: null
  value: true
norm_constant:
  desc: null
  value: 1
sin_embedding:
  desc: null
  value: false
ode_regularization:
  desc: null
  value: 0.001
dataset:
  desc: null
  value: qm9
datadir:
  desc: null
  value: qm9/temp
filter_n_atoms:
  desc: null
  value: null
dequantization:
  desc: null
  value: argmax_variational
n_report_steps:
  desc: null
  value: 1
wandb_usr:
  desc: null
  value: null
no_wandb:
  desc: null
  value: false
online:
  desc: null
  value: true
no_cuda:
  desc: null
  value: false
save_model:
  desc: null
  value: true
generate_epochs:
  desc: null
  value: 1
num_workers:
  desc: null
  value: 0
test_epochs:
  desc: null
  value: 20
data_augmentation:
  desc: null
  value: false
conditioning:
  desc: null
  value: []
resume:
  desc: null
  value: null
start_epoch:
  desc: null
  value: 0
ema_decay:
  desc: null
  value: 0.9999
augment_noise:
  desc: null
  value: 0
n_stability_samples:
  desc: null
  value: 1000
normalize_factors:
  desc: null
  value:
  - 1
  - 4
  - 10
remove_h:
  desc: null
  value: false
include_charges:
  desc: null
  value: true
visualize_every_batch:
  desc: null
  value: 100000000.0
normalization_factor:
  desc: null
  value: 1
aggregation_method:
  desc: null
  value: sum
cuda:
  desc: null
  value: false
_wandb:
  desc: null
  value:
    python_version: 3.11.3
    cli_version: 0.14.1
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1711256612.230762
    t:
      1:
      - 1
      - 55
      3:
      - 13
      - 16
      - 23
      4: 3.11.3
      5: 0.14.1
      8:
      - 5
